language: node_js
node_js:
- 0.10
before_script:
- npm install
- npm install -g grunt-cli
- bower install
script:
- grunt
deploy:
  provider: heroku
  buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
  api_key:
    secure: DJJZmbZe9lXkU63uvQ68u8fKv1rZiNDrZZT9YO42QiyNiFIDNAcVC3Oy+vJwd9WjClgDsfsxO4CqBGIzgtXnLSZHXSWRL2uZaERX8E9Dt4V+MXHtj7dwxNf6QMe4rjyC9cQjhq5xHSkdf4skxdtWjuF4eS/dd/VSzkNEeZ51Xpg=
  app: battle-tracker
  skip_cleanup: true
  on:
    repo: phillipgreenii/battle-tracker
